Fixed studyroomMigration
csvalpha/amber-api pull request #462
Opened 2024-11-13 18:40 UTC by lodewiges

2024-11-13 18:48 UTC, DrumsnChocolate requested changes

2024-11-13 18:48 UTC, DrumsnChocolate commented on db/migrate/20241027103012_create_study_room_presence.rb
The new migration file is invalid ruby. I think you still need to place an extra `end` at the end of the file, to finish the `class`.

2024-11-13 18:50 UTC, lodewiges commented on db/migrate/20241027103012_create_study_room_presence.rb
I am aware, i right now rebuilding my database

2024-11-21 23:00 UTC, DrumsnChocolate approved these changes
haven't tested locally

2024-11-21 23:49 UTC, merged